name:                pandoc-acros
version:             0.1.0.0
github:              "ragreener1/pandoc-acros"
license:             MIT
author:              "Robert Greener"
maintainer:          "rob@robgreener.com"
copyright:           "2020 Robert Greener"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ragreener1/pandoc-acros#readme>

dependencies:
- base >= 4.7 && < 5
- pandoc-types == 1.22
- text
- containers

library:
  source-dirs: src

executables:
  pandoc-acros-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-acros

tests:
  pandoc-acros-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-acros
